//Second image trying to see what can be done

#ifndef TENSORFLOW_LITE_EXPERIMENTAL_MICRO_EXAMPLES_PERSON_DETECTION_PINEAPPLE_192
#define TENSORFLOW_LITE_EXPERIMENTAL_MICRO_EXAMPLES_PERSON_DETECTION_PINEAPPLE_192

#include <cstdint>

extern const int pineapple_data_192_size;
extern const uint8_t pineapple_data_192[];

#endif  // TENSORFLOW_LITE_EXPERIMENTAL_MICRO_EXAMPLES_PERSON_DETECTION_PINEAPPLE_DATA_192_H_
