#! /usr/bin/env python3

import numpy as np
np.random.seed(42)

def write_array(f, a, name):
    s = "const float " + name + "[" + str(len(a)) + "] =\n{\n  "
    for i,x in enumerate(a):
        if i % 10 == 0:
            s += "\n  "
        s += str(x) + ", "
    f.write(s)
    f.write("};\n\n")

t = np.linspace(0, 1, 42*60)
x = (np.sin(2*np.pi*60*t + 2.1) + 0.2* np.sin(2*np.pi*5*t + 1) + 0.1*np.sin(2*np.pi*2*t))
with open("data.c", "w") as f:
    f.write("// Automatically generated by `raw_to_c_array.py'\n\n")
    f.write("#include \"stdint.h\"\n\n")
    f.write("// Raw voltage ADC samples:\n")
    xn = x + np.random.randn(len(t)) * 0.08
    write_array(f, xn, 'voltage')
    f.write("// Raw integration calculation ADC samples:\n")
    xn = x + np.random.randn(len(t)) * 0.08
    write_array(f, xn, 'current')
