/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Fri Oct 11 23:29:17 2019. */

#include "dfu-cc.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool dfu_InitCommand_is_debug_default = false;


const pb_field_t dfu_Hash_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, dfu_Hash, hash_type, hash_type, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, dfu_Hash, hash, hash_type, 0),
    PB_LAST_FIELD
};

const pb_field_t dfu_BootValidation_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, dfu_BootValidation, type, type, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, dfu_BootValidation, bytes, type, 0),
    PB_LAST_FIELD
};

const pb_field_t dfu_InitCommand_fields[11] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, dfu_InitCommand, fw_version, fw_version, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, dfu_InitCommand, hw_version, fw_version, 0),
    PB_FIELD(  3, UINT32  , REPEATED, STATIC  , OTHER, dfu_InitCommand, sd_req, hw_version, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, dfu_InitCommand, type, sd_req, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, dfu_InitCommand, sd_size, type, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, dfu_InitCommand, bl_size, sd_size, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, dfu_InitCommand, app_size, bl_size, 0),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, dfu_InitCommand, hash, app_size, &dfu_Hash_fields),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, dfu_InitCommand, is_debug, hash, &dfu_InitCommand_is_debug_default),
    PB_FIELD( 10, MESSAGE , REPEATED, STATIC  , OTHER, dfu_InitCommand, boot_validation, is_debug, &dfu_BootValidation_fields),
    PB_LAST_FIELD
};

const pb_field_t dfu_Command_fields[3] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, dfu_Command, op_code, op_code, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, dfu_Command, init, op_code, &dfu_InitCommand_fields),
    PB_LAST_FIELD
};

const pb_field_t dfu_SignedCommand_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, dfu_SignedCommand, command, command, &dfu_Command_fields),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, dfu_SignedCommand, signature_type, command, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, STATIC  , OTHER, dfu_SignedCommand, signature, signature_type, 0),
    PB_LAST_FIELD
};

const pb_field_t dfu_Packet_fields[3] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, dfu_Packet, command, command, &dfu_Command_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, dfu_Packet, signed_command, command, &dfu_SignedCommand_fields),
    PB_LAST_FIELD
};







/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(dfu_InitCommand, hash) < 65536 && pb_membersize(dfu_InitCommand, boot_validation[0]) < 65536 && pb_membersize(dfu_Command, init) < 65536 && pb_membersize(dfu_SignedCommand, command) < 65536 && pb_membersize(dfu_Packet, command) < 65536 && pb_membersize(dfu_Packet, signed_command) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_dfu_Hash_dfu_BootValidation_dfu_InitCommand_dfu_Command_dfu_SignedCommand_dfu_Packet)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(dfu_InitCommand, hash) < 256 && pb_membersize(dfu_InitCommand, boot_validation[0]) < 256 && pb_membersize(dfu_Command, init) < 256 && pb_membersize(dfu_SignedCommand, command) < 256 && pb_membersize(dfu_Packet, command) < 256 && pb_membersize(dfu_Packet, signed_command) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_dfu_Hash_dfu_BootValidation_dfu_InitCommand_dfu_Command_dfu_SignedCommand_dfu_Packet)
#endif


/* @@protoc_insertion_point(eof) */
