nrf52840:
  target: nrf52840
  compilers:
    - gcc
    - iar
  required_libs:
    - libopenthread-cli-ftd
    - libopenthread-cli-mtd
    - libopenthread-ftd
    - libopenthread-mtd
    - libopenthread-radio
    - libopenthread-ncp-ftd
    - libopenthread-ncp-ftd-spi
    - libopenthread-ncp-mtd
    - libopenthread-ncp-mtd-spi
    - libopenthread-rcp
    - libopenthread-rcp-spi
    - libopenthread-nrf52840-sdk
    - libopenthread-nrf52840-softdevice-sdk
    - libopenthread-nrf52840-sdk-nodiag
    - libopenthread-nrf52840-softdevice-sdk-nodiag
    - libopenthread-platform-utils
    - libnordicsemi-nrf52840-radio-driver
    - libnordicsemi-nrf52840-radio-driver-softdevice
    - libopenthread-nrf52840-transport
    - libopenthread-nrf52840-transport-usb
    - libopenthread-nrf52840-transport-spi
    - libopenthread-nrf52840-transport-none
    - libopenthread-cli-ftd-optimized-ftd
    - libopenthread-ftd-optimized-ftd
    - libopenthread-platform-utils-optimized-ftd
    - libopenthread-cli-mtd-optimized-mtd
    - libopenthread-mtd-optimized-mtd
    - libopenthread-platform-utils-optimized-mtd
    - libopenthread-spinel-ncp
    - libopenthread-spinel-rcp
    - libopenthread-hdlc
  dropped_libs:
    - libjlinkrtt
    - libnordicsemi-nrf52840-sdk
    - libopenthread-nrf52840
    - libmbedcrypto


keil:
  target: nrf52840
  compilers:
    - keil
  required_libs:
    - libmbedcrypto
    - libopenthread-cli-ftd
    - libopenthread-cli-mtd
    - libopenthread-ftd
    - libopenthread-mtd
    - libopenthread-radio
    - libopenthread-ncp-ftd
    - libopenthread-ncp-ftd-spi
    - libopenthread-ncp-mtd
    - libopenthread-ncp-mtd-spi
    - libopenthread-rcp
    - libopenthread-rcp-spi
    - libopenthread-nrf52840-sdk
    - libopenthread-nrf52840-softdevice-sdk
    - libopenthread-nrf52840-sdk-nodiag
    - libopenthread-nrf52840-softdevice-sdk-nodiag
    - libopenthread-platform-utils
    - libnordicsemi-nrf52840-radio-driver
    - libnordicsemi-nrf52840-radio-driver-softdevice
    - libopenthread-nrf52840-transport
    - libopenthread-nrf52840-transport-usb
    - libopenthread-nrf52840-transport-spi
    - libopenthread-nrf52840-transport-none
    - libopenthread-cli-ftd-optimized-ftd
    - libopenthread-ftd-optimized-ftd
    - libopenthread-platform-utils-optimized-ftd
    - libopenthread-cli-mtd-optimized-mtd
    - libopenthread-mtd-optimized-mtd
    - libopenthread-platform-utils-optimized-mtd
    - libopenthread-spinel-ncp
    - libopenthread-spinel-rcp
    - libopenthread-hdlc
  dropped_libs:
    - libjlinkrtt
    - libnordicsemi-nrf52840-sdk
    - libopenthread-nrf52840


nrf52833:
  target: nrf52833
  compilers:
    - gcc
    - keil
    - iar
  required_libs:
    - libmbedcrypto
    - libopenthread-cli-ftd
    - libopenthread-cli-mtd
    - libopenthread-ftd
    - libopenthread-mtd
    - libopenthread-radio
    - libopenthread-ncp-ftd
    - libopenthread-ncp-ftd-spi
    - libopenthread-ncp-mtd
    - libopenthread-ncp-mtd-spi
    - libopenthread-rcp
    - libopenthread-rcp-spi
    - libopenthread-nrf52833-sdk
    - libopenthread-nrf52833-softdevice-sdk
    - libopenthread-nrf52833-sdk-nodiag
    - libopenthread-nrf52833-softdevice-sdk-nodiag
    - libopenthread-platform-utils
    - libnordicsemi-nrf52833-radio-driver
    - libnordicsemi-nrf52833-radio-driver-softdevice
    - libopenthread-nrf52833-transport
    - libopenthread-nrf52833-transport-usb
    - libopenthread-nrf52833-transport-spi
    - libopenthread-nrf52833-transport-none
    - libopenthread-cli-ftd-optimized-ftd
    - libopenthread-ftd-optimized-ftd
    - libopenthread-platform-utils-optimized-ftd
    - libopenthread-cli-mtd-optimized-mtd
    - libopenthread-mtd-optimized-mtd
    - libopenthread-platform-utils-optimized-mtd
    - libopenthread-spinel-ncp
    - libopenthread-spinel-rcp
    - libopenthread-hdlc
  dropped_libs:
    - libjlinkrtt
    - libnordicsemi-nrf52833-sdk
    - libopenthread-nrf52833

nrf52811:
  target: nrf52811
  compilers:
    - gcc
    - iar
    - keil
  required_libs:
    - libmbedcrypto
    - libopenthread-cli-mtd
    - libopenthread-mtd
    - libopenthread-radio
    - libopenthread-rcp
    - libopenthread-rcp-spi
    - libopenthread-nrf52811-sdk
    - libopenthread-platform-utils
    - libnordicsemi-nrf52811-radio-driver
    - libopenthread-nrf52811-transport
    - libopenthread-nrf52811-transport-spi
    - libopenthread-nrf52811-transport-none
    - libopenthread-spinel-ncp
    - libopenthread-spinel-rcp
    - libopenthread-hdlc
  dropped_libs:
    - libjlinkrtt
    - libnordicsemi-nrf52811-sdk
    - libopenthread-nrf52811
    - libopenthread-ftd
    - libopenthread-cli-ftd
    - libopenthread-ncp-ftd
    - libopenthread-ncp-ftd-spi
    - libopenthread-ncp-mtd
    - libopenthread-ncp-mtd-spi
    - libopenthread-nrf52811-softdevice-sdk
    - libnordicsemi-nrf52811-radio-driver-softdevice
    - libopenthread-nrf52811-transport-usb
    - libopenthread-cli-ftd-optimized-ftd
    - libopenthread-ftd-optimized-ftd
    - libopenthread-platform-utils-optimized-ftd
    - libopenthread-cli-mtd-optimized-mtd
    - libopenthread-mtd-optimized-mtd
    - libopenthread-platform-utils-optimized-mtd
    - libopenthread-nrf52811-sdk-nodiag
    - libopenthread-nrf52811-softdevice-sdk-nodiag


